// MIT License
// 
// Copyright (c) 2015-2024 Vector 35 Inc
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#ifndef TESTPLUGIN_LIBRARY_H
#define TESTPLUGIN_LIBRARY_H

#include "binaryninjaapi.h"

#endif //TESTPLUGIN_LIBRARY_H

enum insn_names {
    INVALID_INSN,
    SE_MTCTR,
    SE_MFCTR,
    SE_MFLR,
    SE_MTSPR,
    SE_MFSPR,
    SE_BCTR,
    SE_BCTRL,
    E_LIS,
    E_LI,
    SE_LI,
    SE_MR,
    SE_MFAR,
    SE_MTAR,
    SE_ADD,
    E_ADD2I,
    SE_ADDI,
    E_ADD2IS,
    E_ADD16I,
    E_ADDI,
    E_STWU,
    E_STHU,
    E_STBU,
    E_STW,
    SE_STW,
    E_STH,
    SE_STH,
    E_STB,
    SE_STB,
    SE_LWZ,
    E_LWZ,
    E_LHZ,
    SE_LHZ,
    SE_LBZ,
    E_LBZ,
    E_LBZU,
    E_LHZU,
    E_LWZU,
    SE_CMP,
    E_CMPH,
    SE_CMPH,
    SE_CMPHL,
    SE_CMPHL16I,
    SE_CMPI,
    SE_CMPL,
    SE_CMPLI,
    E_CMPLI,
    E_CMPL16I,
    E_CMPI,
    SE_EXTZB,
    SE_EXTZH,
    SE_EXTSB,
    SE_EXTSH,
    E_MULLI,
    E_MULL2I,
    SE_MULLW,
    SE_NEG,
    SE_NOT,
    SE_OR,
    E_ORI,
    E_OR2I,
    E_OR2IS,
    E_RLW,
    E_RLWI,
    E_RLWINM,
    E_RLWIMI,
    E_SLWI,
    SE_SLW,
    SE_SLWI,
    SE_SRAW,
    SE_SRAWI,
    E_SRWI,
    SE_SRW,
    SE_SRWI,
    E_STMW,
    SE_SUB,
    SE_SUBF,
    E_SUBFIC,
    SE_SUBI,
    E_XORI,
    SE_MTLR,
    E_LMW,
    SE_AND,
    SE_ANDI,
    SE_ANDC,
    E_ANDI,
    E_AND2I,
    E_AND2IS,
    SE_BMASKI,
    E_LHA,
    E_LHAU,
    SE_BTSTI,
    SE_BSETI,
    SE_BGENI,
    E_ADDIC,
    SE_BCLRI,
    E_CMPHL16I,
    E_CMP16I,
    SE_SC,
    E_CMPH16I,
    E_CRAND,
    E_CRANDC,
    E_MCRF,
    EFSABS,
    EFSADD,
    EFSCFH,
    EFSCFSF,
    EFSCFSI,
    EFSCFUF,
    EFSCFUI,
    EFSCMPGT,
    EFSCMPEQ,
    EFSCMPLT,
    EFSCTH,
    EFSCTSF,
    EFSCTSI,
    EFSCTSIZ,
    EFSCTUF,
    EFSCTUI,
    EFSCTUIZ,
    EFSDIV,
    EFSMADD,
    EFSMAX,
    EFSMIN,
    EFSMSUB,
    EFSMUL,
    EFSNABS,
    EFSNEG,
    EFSNMADD,
    EFSNMSUB,
    EFSSQRT,
    EFSSUB,
    EFSTSTEQ,
    EFSTSTGT,
    EFSTSTLT,
    E_LDMVGPRW,
    E_STMVGPRW,
    SE_ILLEGAL
};
