name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        - {
            os: windows-2019,
            name: windows
          }
        - {
            os: macos-13,
            name: macos
          }
        - {
            os: ubuntu-22.04,
            name: ubuntu
          }
        version: 
        - v03.02.03814
        - v3.3.3996
        - v3.4.4271-stable
        - v3.5.4526-stable
        - v4.0.4958-stable ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Update submodule
      run: |
        cd binaryninjaapi
        git fetch --tags
        git checkout --force ${{matrix.version}}
        git submodule update --init --recursive
    - name: Patch api to allow building headlessly (>= 4.0)
      runs-on: v4.0.4958-stable
      run: |
        cd binaryninjaapi
        git apply --verbose ../.github/workflows/0001-Support-building-plugins-without-an-install.patch
    - name: Patch api to allow building headlessly (< 4.0)
      runs-on: 
      - v03.02.03814
      - v3.3.3996
      - v3.4.4271-stable
      - v3.5.4526-stable
      run: |
        cd binaryninjaapi
        git apply --verbose ../.github/workflows/0001-Support-building-plugins-without-an-install.patch
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.config.name}}-${{matrix.version}}
        path: ${{github.workspace}}/build/*TestPlugin*
